---
title: "Stock-Bot"
author: "SNTag"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    css: style.css
    number_sections: false
    toc: false
    toc_depth: 3
    fig_caption: true
    fig_width: 7
    fig_height: 4
    includes:
      in_header: my_header.tex
---

# Description

My stock-bot is being reprogrammed in R. This is a work in progress.

## Purpose

It will run once a day, at the end of the trading session, using free api sources. As such, efficiency is not the goal, and can run for a notable period of time.

This script will pull information from a financial api, and process it. It's main purpose is to alert to abnormalities in the data (ex., stock going under or doing unusually well). It will also pump out extra data as a side effect (graphs, producing ratios, etc).

## Why I made this

This is a simple bot to keep me updated on my investments. I am a lazy investor; I don't want to baby-sit my investments.

This script is designed for a headless server (for a VPS, or a simple raspberry pi). Abnormalities in data will be reported using a notifier.

I rewrote this script from python as I prefer the R language. I have also begun to understand it in greater depth than python, and see advantages in using R for further data analysis.

# To Use

Keep note that the file "./stock.csv" is an example file. Please replace with your own.

The main script is "./stock-bot.R". If you have not provided key details, it will ask you for them.

To add the stock-bot to crontab, to run everyday at 11:00AM, run 'setup.sh'.

## Prerequisites

### setting up the fundamentals and notifications

### Setting up data collection

### Add stocks of interest

## To Use

# Technical details

These details are unnecessary for everyday usage. They refer to how the script functions.

## Tracking companies and the investment plan they are under

Using a basic csv sheet, each company and the plan they are under are read. Informing the program what investment plan they are under is important only to the notifications you receive.

The csv sheet should look as such:

| stocks  | investment.plan  |
|---|---|
| TickerA  | planA  |
| TickerB  | planB  |
| TickerC  | planC  |

## Notifications

**NOTE**
To disable any notifications and to use this as only a data-download service, add this line in '/input/config.yaml' after running '/config-editor.py';

`msg_status: 'false'`

User needs to set up an appropiate notification system. Current approaches work:

- slack (notifier_key is made as described here: https://api.slack.com/messaging/webhooks)

in development:

- ifttt

### slack

For each alert set, all stocks triggering the alarm will be sent as such:

"these stocks are  decreasing_greatly  :  stock1, stock2, stock3, stock4, stock5"

## Data collection

Restricted to only collecting data for now. Will not save previous sheets collected from financial apis.

Uses only Alpha Vantage for now.

Data collection is done only once a day.

Data is save to "./data/data.RData". It can be accessed using 'load("./data/data.RData")'.

## setup config

options to setup config:
- If it does not exist, I recommend running the python script "./setup-config.py".
- modified manually by directly editing "./config".
- If it exists, but a guided edit is desired, run "./setup-config.py".

## input stocks

stocks to consider are to be placed in "./stocks.csv". see 'tracking companies and the investment plan they are under' for how to setup the csv.

The script will read the "./stocks.csv" at the start. As the script is designed to be run fresh every time, it will reread the csv file. As such, modifications to stocks to be considered can be done on the fly.

## alerts

### changing conditions for alerts

You need to know R to change the alerts. Edit the file "./alerts.R".

**IMPORTANT**
Each alert needs to return a named list as such: "stck" = "condition msg". For example, one alert that comes with this stock bot is for decreasing greatly.

```{R, echo = T, eval = F}
alerts$condition2 <-
    function(x, stck) {
        x <- quantmod::periodReturn(x)
        tmpList <- setNames("decreasing_greatly", stck[1])
        if (x[1,1] < -0.05) {return(tmpList)}
        return("failed")
    }
```

For MSFT, the above would return a list such as c("MSFT": "decreasing_greatly")

A yaml option for setting alerts may come eventually.

### keeping record of banned companies

Managed using an R rds object. Holds a list of stock names as element names, representing a date. The date informs when the stock is to be taken OFF the banned list.

### banned stocks

Banned stocks are those that have triggered an alert. For example, excessive decline in price. notifications will be sent once per alert, and then ignored for a week. The program keeps track of banned stocks in the file "./banned-list.rds"
